services:
  db:
    container_name: "db"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "smart-parking"
      TZ: "America/Bogota"
    image: "mysql:9.0.1"
    networks:
      - default
    ports:
      - "33060:3306"
    volumes:
      - "datos:/var/lib/mysql"
      - "./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
volumes:
  datos:
    name: "datos"
